sudo: required

language: python

jobs:
  include:
    - os: linux
      dist: focal
      group: edge
      arch: arm64-graviton2
      virt: vm
      python: "3.6"
    - os: linux
      dist: focal
      group: edge
      arch: arm64-graviton2
      virt: vm
      python: "3.7"
    - os: linux
      dist: focal
      group: edge
      arch: arm64-graviton2
      python: "3.8"
      virt: vm

services:
- docker

env:
  global:
    - CIBW_SKIP: cp35-manylinux_aarch64
    - CIBW_MANYLINUX_AARCH64_IMAGE: manylinux2014

before_install:
  - cd sdks/python
  - python -m pip install -r build-requirements.txt
  - python -m pip install wheel
  - pip install -U pip cibuildwheel==1.4.2 cython
  - pip uninstall -y protobuf
  - pip uninstall -y google
  - pip install -y protobuf google google-cloud google-cloud-bigquery
  
script:
  - python setup.py sdist --formats=zip
  #- python setup.py sdist --formats=zip
  - file=$(ls | grep .zip | head -n 1)
  #- sha512sum $file > ${file}.sha512
  - unzip dist/$(ls dist | grep .zip | head -n 1)
  - mv $(ls | grep apache-beam) apache-beam-source
  - cibuildwheel --print-build-identifiers --platform linux && cibuildwheel --output-dir wheelhouse  
  #- cibuildwheel --output-dir wheelhouse
  - python setup.py bdist_wheel 
  - cd dist
  - ls
  - cd ../wheelhouse
  - ls
